<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="lidar_frame"/>
        <origin xyz="${chassis_length/2} 0 0.105" rpy="${pi} 0 0"/>
    </joint>

    <link name="lidar_frame">
        <visual>
            <geometry>
                <cylinder radius="0.018" length="0.01"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
    </link>


    <gazebo reference="lidar_frame">
        <material>Gazebo/Black</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.0005</min>
                    <max>15</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_laser.so">
                <topicName>/LiDAR/LD19</topicName>
                <frameName>lidar_frame</frameName>
            </plugin>
        </sensor>
    </gazebo>

</robot>
